// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb69bprFxZADgxNcZGCq_2xaqHdX-f5ds',
    appId: '1:295152563636:web:21afbfa0c6fc0bf060eee1',
    messagingSenderId: '295152563636',
    projectId: 'coingecko-bc7d0',
    authDomain: 'coingecko-bc7d0.firebaseapp.com',
    storageBucket: 'coingecko-bc7d0.firebasestorage.app',
    measurementId: 'G-677ZXDJW6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2PBdnuTW03dw-VFenF4Nc6U-zxx5QmKM',
    appId: '1:295152563636:android:9cba0fd5b5a0391260eee1',
    messagingSenderId: '295152563636',
    projectId: 'coingecko-bc7d0',
    storageBucket: 'coingecko-bc7d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmxrwWFoVAGz8i9UzAnqSUqbGmj5txgc8',
    appId: '1:295152563636:ios:8de8653058e464e660eee1',
    messagingSenderId: '295152563636',
    projectId: 'coingecko-bc7d0',
    storageBucket: 'coingecko-bc7d0.firebasestorage.app',
    iosBundleId: 'com.example.blockchain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmxrwWFoVAGz8i9UzAnqSUqbGmj5txgc8',
    appId: '1:295152563636:ios:8de8653058e464e660eee1',
    messagingSenderId: '295152563636',
    projectId: 'coingecko-bc7d0',
    storageBucket: 'coingecko-bc7d0.firebasestorage.app',
    iosBundleId: 'com.example.blockchain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb69bprFxZADgxNcZGCq_2xaqHdX-f5ds',
    appId: '1:295152563636:web:5219de8d44858afd60eee1',
    messagingSenderId: '295152563636',
    projectId: 'coingecko-bc7d0',
    authDomain: 'coingecko-bc7d0.firebaseapp.com',
    storageBucket: 'coingecko-bc7d0.firebasestorage.app',
    measurementId: 'G-0G1CBG56F9',
  );
}
